set_property SRC_FILE_INFO {cfile:D:/Dev/CENG342/Lab_12/Lab_12.srcs/constrs_1/imports/Computer_package/DDR2.xdc rfile:../../../Lab_12.srcs/constrs_1/imports/Computer_package/DDR2.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Dev/CENG342/Lab_12/Lab_12.srcs/constrs_1/imports/Computer_package/Nexys-A7-100T-Master.xdc rfile:../../../Lab_12.srcs/constrs_1/imports/Computer_package/Nexys-A7-100T-Master.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Dev/CENG342/Lab_12/Lab_12.srcs/constrs_1/imports/Computer_package/bitstream_settings.xdc rfile:../../../Lab_12.srcs/constrs_1/imports/Computer_package/bitstream_settings.xdc id:3} [current_design]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports {ddr2_dq[0]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports {ddr2_dq[1]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports {ddr2_dq[2]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports {ddr2_dq[3]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports {ddr2_dq[4]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R6 [get_ports {ddr2_dq[5]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports {ddr2_dq[6]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R5 [get_ports {ddr2_dq[7]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports {ddr2_dq[8]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U3 [get_ports {ddr2_dq[9]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {ddr2_dq[10]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports {ddr2_dq[11]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {ddr2_dq[12]}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports {ddr2_dq[13]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1 [get_ports {ddr2_dq[14]}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports {ddr2_dq[15]}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N6 [get_ports {ddr2_addr[12]}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports {ddr2_addr[11]}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {ddr2_addr[10]}]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N5 [get_ports {ddr2_addr[9]}]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports {ddr2_addr[8]}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1 [get_ports {ddr2_addr[7]}]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports {ddr2_addr[6]}]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports {ddr2_addr[5]}]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3 [get_ports {ddr2_addr[4]}]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports {ddr2_addr[3]}]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports {ddr2_addr[2]}]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports {ddr2_addr[1]}]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M4 [get_ports {ddr2_addr[0]}]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R1 [get_ports {ddr2_ba[2]}]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports {ddr2_ba[1]}]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P2 [get_ports {ddr2_ba[0]}]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N4 [get_ports ddr2_ras_n]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports ddr2_cas_n]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N2 [get_ports ddr2_we_n]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports ddr2_cke]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M3 [get_ports ddr2_odt]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K6 [get_ports ddr2_cs_n]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports {ddr2_dm[0]}]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports {ddr2_dm[1]}]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dqs_p[0]}]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dqs_p[0]}]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports {ddr2_dqs_p[0]}]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U9 [get_ports {ddr2_dqs_p[0]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports {ddr2_dqs_n[0]}]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dqs_p[1]}]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dqs_p[1]}]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports {ddr2_dqs_p[1]}]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports {ddr2_dqs_p[1]}]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2 [get_ports {ddr2_dqs_n[1]}]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L6 [get_ports ddr2_ck_p]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L5 [get_ports ddr2_ck_n]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y81 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y57 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr2_infrastructure/plle2_i}]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr2_infrastructure/gen_mmcm.mmcm_i}]
set_property src_info {type:XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] -setup 6
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] -hold 5
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins -filter {NAME =~ */DQSFOUND} -of [get_cells -hier -filter {REF_NAME == PHASER_IN_PHY}]]
set_property src_info {type:XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -setup 2 -start
set_property src_info {type:XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -hold 1 -start
set_property src_info {type:XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -to [get_pins -hier -include_replicated_objects -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1_reg[*]/D}] 20
set_property src_info {type:XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
set_property src_info {type:XDC file:1 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets -hier -filter {NAME =~ */u_iodelay_ctrl/sys_rst_i}]
set_property src_info {type:XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr2_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clock]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {switches[0]}]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {switches[1]}]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {switches[2]}]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports {switches[3]}]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {switches[4]}]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {switches[5]}]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {switches[6]}]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R13 IOSTANDARD LVCMOS33} [get_ports {switches[7]}]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T8 IOSTANDARD LVCMOS18} [get_ports {switches[8]}]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U8 IOSTANDARD LVCMOS18} [get_ports {switches[9]}]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {switches[10]}]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T13 IOSTANDARD LVCMOS33} [get_ports {switches[11]}]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS33} [get_ports {switches[12]}]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {switches[13]}]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U11 IOSTANDARD LVCMOS33} [get_ports {switches[14]}]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports {switches[15]}]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {leds[0]}]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports {leds[1]}]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports {leds[2]}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports {leds[3]}]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {leds[4]}]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {leds[5]}]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {leds[6]}]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33} [get_ports {leds[7]}]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports {leds[8]}]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {leds[9]}]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports {leds[10]}]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {leds[11]}]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports {leds[12]}]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS33} [get_ports {leds[13]}]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports {leds[14]}]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V11 IOSTANDARD LVCMOS33} [get_ports {leds[15]}]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R12 IOSTANDARD LVCMOS33} [get_ports {rgb_leds[0]}]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33} [get_ports {rgb_leds[1]}]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports {rgb_leds[2]}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33} [get_ports {rgb_leds[3]}]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R11 IOSTANDARD LVCMOS33} [get_ports {rgb_leds[4]}]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports {rgb_leds[5]}]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {sseg[0]}]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R10 IOSTANDARD LVCMOS33} [get_ports {sseg[1]}]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {sseg[2]}]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports {sseg[3]}]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {sseg[4]}]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports {sseg[5]}]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {sseg[6]}]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports {sseg[7]}]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {sseg_an[0]}]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {sseg_an[1]}]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {sseg_an[2]}]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {sseg_an[3]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {sseg_an[4]}]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {sseg_an[5]}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {sseg_an[6]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {sseg_an[7]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports reset]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {buttons[0]}]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports {buttons[1]}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports {buttons[2]}]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports {buttons[3]}]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports {buttons[4]}]
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS33} [get_ports RXD]
set_property src_info {type:XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports TXD]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clkgen/inst/clk_50]]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {CPU/datapath/RegisterFile/output[4]_3[0]} {CPU/datapath/RegisterFile/output[4]_3[1]} {CPU/datapath/RegisterFile/output[4]_3[2]} {CPU/datapath/RegisterFile/output[4]_3[3]} {CPU/datapath/RegisterFile/output[4]_3[4]} {CPU/datapath/RegisterFile/output[4]_3[5]} {CPU/datapath/RegisterFile/output[4]_3[6]} {CPU/datapath/RegisterFile/output[4]_3[7]} {CPU/datapath/RegisterFile/output[4]_3[8]} {CPU/datapath/RegisterFile/output[4]_3[9]} {CPU/datapath/RegisterFile/output[4]_3[10]} {CPU/datapath/RegisterFile/output[4]_3[11]} {CPU/datapath/RegisterFile/output[4]_3[12]} {CPU/datapath/RegisterFile/output[4]_3[13]} {CPU/datapath/RegisterFile/output[4]_3[14]} {CPU/datapath/RegisterFile/output[4]_3[15]} {CPU/datapath/RegisterFile/output[4]_3[16]} {CPU/datapath/RegisterFile/output[4]_3[17]} {CPU/datapath/RegisterFile/output[4]_3[18]} {CPU/datapath/RegisterFile/output[4]_3[19]} {CPU/datapath/RegisterFile/output[4]_3[20]} {CPU/datapath/RegisterFile/output[4]_3[21]} {CPU/datapath/RegisterFile/output[4]_3[22]} {CPU/datapath/RegisterFile/output[4]_3[23]} {CPU/datapath/RegisterFile/output[4]_3[24]} {CPU/datapath/RegisterFile/output[4]_3[25]} {CPU/datapath/RegisterFile/output[4]_3[26]} {CPU/datapath/RegisterFile/output[4]_3[27]} {CPU/datapath/RegisterFile/output[4]_3[28]} {CPU/datapath/RegisterFile/output[4]_3[29]} {CPU/datapath/RegisterFile/output[4]_3[30]} {CPU/datapath/RegisterFile/output[4]_3[31]}]]
set_property src_info {type:XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {CPU/datapath/RegisterFile/output[0]_7[0]} {CPU/datapath/RegisterFile/output[0]_7[1]} {CPU/datapath/RegisterFile/output[0]_7[2]} {CPU/datapath/RegisterFile/output[0]_7[3]} {CPU/datapath/RegisterFile/output[0]_7[4]} {CPU/datapath/RegisterFile/output[0]_7[5]} {CPU/datapath/RegisterFile/output[0]_7[6]} {CPU/datapath/RegisterFile/output[0]_7[7]} {CPU/datapath/RegisterFile/output[0]_7[8]} {CPU/datapath/RegisterFile/output[0]_7[9]} {CPU/datapath/RegisterFile/output[0]_7[10]} {CPU/datapath/RegisterFile/output[0]_7[11]} {CPU/datapath/RegisterFile/output[0]_7[12]} {CPU/datapath/RegisterFile/output[0]_7[13]} {CPU/datapath/RegisterFile/output[0]_7[14]} {CPU/datapath/RegisterFile/output[0]_7[15]} {CPU/datapath/RegisterFile/output[0]_7[16]} {CPU/datapath/RegisterFile/output[0]_7[17]} {CPU/datapath/RegisterFile/output[0]_7[18]} {CPU/datapath/RegisterFile/output[0]_7[19]} {CPU/datapath/RegisterFile/output[0]_7[20]} {CPU/datapath/RegisterFile/output[0]_7[21]} {CPU/datapath/RegisterFile/output[0]_7[22]} {CPU/datapath/RegisterFile/output[0]_7[23]} {CPU/datapath/RegisterFile/output[0]_7[24]} {CPU/datapath/RegisterFile/output[0]_7[25]} {CPU/datapath/RegisterFile/output[0]_7[26]} {CPU/datapath/RegisterFile/output[0]_7[27]} {CPU/datapath/RegisterFile/output[0]_7[28]} {CPU/datapath/RegisterFile/output[0]_7[29]} {CPU/datapath/RegisterFile/output[0]_7[30]} {CPU/datapath/RegisterFile/output[0]_7[31]}]]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:3 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {CPU/datapath/RegisterFile/output[6]_1[0]} {CPU/datapath/RegisterFile/output[6]_1[1]} {CPU/datapath/RegisterFile/output[6]_1[2]} {CPU/datapath/RegisterFile/output[6]_1[3]} {CPU/datapath/RegisterFile/output[6]_1[4]} {CPU/datapath/RegisterFile/output[6]_1[5]} {CPU/datapath/RegisterFile/output[6]_1[6]} {CPU/datapath/RegisterFile/output[6]_1[7]} {CPU/datapath/RegisterFile/output[6]_1[8]} {CPU/datapath/RegisterFile/output[6]_1[9]} {CPU/datapath/RegisterFile/output[6]_1[10]} {CPU/datapath/RegisterFile/output[6]_1[11]} {CPU/datapath/RegisterFile/output[6]_1[12]} {CPU/datapath/RegisterFile/output[6]_1[13]} {CPU/datapath/RegisterFile/output[6]_1[14]} {CPU/datapath/RegisterFile/output[6]_1[15]} {CPU/datapath/RegisterFile/output[6]_1[16]} {CPU/datapath/RegisterFile/output[6]_1[17]} {CPU/datapath/RegisterFile/output[6]_1[18]} {CPU/datapath/RegisterFile/output[6]_1[19]} {CPU/datapath/RegisterFile/output[6]_1[20]} {CPU/datapath/RegisterFile/output[6]_1[21]} {CPU/datapath/RegisterFile/output[6]_1[22]} {CPU/datapath/RegisterFile/output[6]_1[23]} {CPU/datapath/RegisterFile/output[6]_1[24]} {CPU/datapath/RegisterFile/output[6]_1[25]} {CPU/datapath/RegisterFile/output[6]_1[26]} {CPU/datapath/RegisterFile/output[6]_1[27]} {CPU/datapath/RegisterFile/output[6]_1[28]} {CPU/datapath/RegisterFile/output[6]_1[29]} {CPU/datapath/RegisterFile/output[6]_1[30]} {CPU/datapath/RegisterFile/output[6]_1[31]}]]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:3 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {CPU/datapath/RegisterFile/output[7]_0[0]} {CPU/datapath/RegisterFile/output[7]_0[1]} {CPU/datapath/RegisterFile/output[7]_0[2]} {CPU/datapath/RegisterFile/output[7]_0[3]} {CPU/datapath/RegisterFile/output[7]_0[4]} {CPU/datapath/RegisterFile/output[7]_0[5]} {CPU/datapath/RegisterFile/output[7]_0[6]} {CPU/datapath/RegisterFile/output[7]_0[7]} {CPU/datapath/RegisterFile/output[7]_0[8]} {CPU/datapath/RegisterFile/output[7]_0[9]} {CPU/datapath/RegisterFile/output[7]_0[10]} {CPU/datapath/RegisterFile/output[7]_0[11]} {CPU/datapath/RegisterFile/output[7]_0[12]} {CPU/datapath/RegisterFile/output[7]_0[13]} {CPU/datapath/RegisterFile/output[7]_0[14]} {CPU/datapath/RegisterFile/output[7]_0[15]} {CPU/datapath/RegisterFile/output[7]_0[16]} {CPU/datapath/RegisterFile/output[7]_0[17]} {CPU/datapath/RegisterFile/output[7]_0[18]} {CPU/datapath/RegisterFile/output[7]_0[19]} {CPU/datapath/RegisterFile/output[7]_0[20]} {CPU/datapath/RegisterFile/output[7]_0[21]} {CPU/datapath/RegisterFile/output[7]_0[22]} {CPU/datapath/RegisterFile/output[7]_0[23]} {CPU/datapath/RegisterFile/output[7]_0[24]} {CPU/datapath/RegisterFile/output[7]_0[25]} {CPU/datapath/RegisterFile/output[7]_0[26]} {CPU/datapath/RegisterFile/output[7]_0[27]} {CPU/datapath/RegisterFile/output[7]_0[28]} {CPU/datapath/RegisterFile/output[7]_0[29]} {CPU/datapath/RegisterFile/output[7]_0[30]} {CPU/datapath/RegisterFile/output[7]_0[31]}]]
set_property src_info {type:XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:3 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {CPU/datapath/AdressI[0]} {CPU/datapath/AdressI[1]} {CPU/datapath/AdressI[2]} {CPU/datapath/AdressI[3]} {CPU/datapath/AdressI[4]} {CPU/datapath/AdressI[5]} {CPU/datapath/AdressI[6]} {CPU/datapath/AdressI[7]} {CPU/datapath/AdressI[8]} {CPU/datapath/AdressI[9]} {CPU/datapath/AdressI[10]} {CPU/datapath/AdressI[11]} {CPU/datapath/AdressI[12]} {CPU/datapath/AdressI[13]} {CPU/datapath/AdressI[14]} {CPU/datapath/AdressI[15]} {CPU/datapath/AdressI[16]} {CPU/datapath/AdressI[17]} {CPU/datapath/AdressI[18]} {CPU/datapath/AdressI[19]} {CPU/datapath/AdressI[20]} {CPU/datapath/AdressI[21]} {CPU/datapath/AdressI[22]} {CPU/datapath/AdressI[23]} {CPU/datapath/AdressI[24]} {CPU/datapath/AdressI[25]} {CPU/datapath/AdressI[26]} {CPU/datapath/AdressI[27]} {CPU/datapath/AdressI[28]} {CPU/datapath/AdressI[29]} {CPU/datapath/AdressI[30]} {CPU/datapath/AdressI[31]}]]
set_property src_info {type:XDC file:3 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {CPU/datapath/RegisterFile/output[1]_6[0]} {CPU/datapath/RegisterFile/output[1]_6[1]} {CPU/datapath/RegisterFile/output[1]_6[2]} {CPU/datapath/RegisterFile/output[1]_6[3]} {CPU/datapath/RegisterFile/output[1]_6[4]} {CPU/datapath/RegisterFile/output[1]_6[5]} {CPU/datapath/RegisterFile/output[1]_6[6]} {CPU/datapath/RegisterFile/output[1]_6[7]} {CPU/datapath/RegisterFile/output[1]_6[8]} {CPU/datapath/RegisterFile/output[1]_6[9]} {CPU/datapath/RegisterFile/output[1]_6[10]} {CPU/datapath/RegisterFile/output[1]_6[11]} {CPU/datapath/RegisterFile/output[1]_6[12]} {CPU/datapath/RegisterFile/output[1]_6[13]} {CPU/datapath/RegisterFile/output[1]_6[14]} {CPU/datapath/RegisterFile/output[1]_6[15]} {CPU/datapath/RegisterFile/output[1]_6[16]} {CPU/datapath/RegisterFile/output[1]_6[17]} {CPU/datapath/RegisterFile/output[1]_6[18]} {CPU/datapath/RegisterFile/output[1]_6[19]} {CPU/datapath/RegisterFile/output[1]_6[20]} {CPU/datapath/RegisterFile/output[1]_6[21]} {CPU/datapath/RegisterFile/output[1]_6[22]} {CPU/datapath/RegisterFile/output[1]_6[23]} {CPU/datapath/RegisterFile/output[1]_6[24]} {CPU/datapath/RegisterFile/output[1]_6[25]} {CPU/datapath/RegisterFile/output[1]_6[26]} {CPU/datapath/RegisterFile/output[1]_6[27]} {CPU/datapath/RegisterFile/output[1]_6[28]} {CPU/datapath/RegisterFile/output[1]_6[29]} {CPU/datapath/RegisterFile/output[1]_6[30]} {CPU/datapath/RegisterFile/output[1]_6[31]}]]
set_property src_info {type:XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:3 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {CPU/datapath/RegisterFile/output[2]_5[0]} {CPU/datapath/RegisterFile/output[2]_5[1]} {CPU/datapath/RegisterFile/output[2]_5[2]} {CPU/datapath/RegisterFile/output[2]_5[3]} {CPU/datapath/RegisterFile/output[2]_5[4]} {CPU/datapath/RegisterFile/output[2]_5[5]} {CPU/datapath/RegisterFile/output[2]_5[6]} {CPU/datapath/RegisterFile/output[2]_5[7]} {CPU/datapath/RegisterFile/output[2]_5[8]} {CPU/datapath/RegisterFile/output[2]_5[9]} {CPU/datapath/RegisterFile/output[2]_5[10]} {CPU/datapath/RegisterFile/output[2]_5[11]} {CPU/datapath/RegisterFile/output[2]_5[12]} {CPU/datapath/RegisterFile/output[2]_5[13]} {CPU/datapath/RegisterFile/output[2]_5[14]} {CPU/datapath/RegisterFile/output[2]_5[15]} {CPU/datapath/RegisterFile/output[2]_5[16]} {CPU/datapath/RegisterFile/output[2]_5[17]} {CPU/datapath/RegisterFile/output[2]_5[18]} {CPU/datapath/RegisterFile/output[2]_5[19]} {CPU/datapath/RegisterFile/output[2]_5[20]} {CPU/datapath/RegisterFile/output[2]_5[21]} {CPU/datapath/RegisterFile/output[2]_5[22]} {CPU/datapath/RegisterFile/output[2]_5[23]} {CPU/datapath/RegisterFile/output[2]_5[24]} {CPU/datapath/RegisterFile/output[2]_5[25]} {CPU/datapath/RegisterFile/output[2]_5[26]} {CPU/datapath/RegisterFile/output[2]_5[27]} {CPU/datapath/RegisterFile/output[2]_5[28]} {CPU/datapath/RegisterFile/output[2]_5[29]} {CPU/datapath/RegisterFile/output[2]_5[30]} {CPU/datapath/RegisterFile/output[2]_5[31]}]]
set_property src_info {type:XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {CPU/datapath/RegisterFile/output[5]_2[0]} {CPU/datapath/RegisterFile/output[5]_2[1]} {CPU/datapath/RegisterFile/output[5]_2[2]} {CPU/datapath/RegisterFile/output[5]_2[3]} {CPU/datapath/RegisterFile/output[5]_2[4]} {CPU/datapath/RegisterFile/output[5]_2[5]} {CPU/datapath/RegisterFile/output[5]_2[6]} {CPU/datapath/RegisterFile/output[5]_2[7]} {CPU/datapath/RegisterFile/output[5]_2[8]} {CPU/datapath/RegisterFile/output[5]_2[9]} {CPU/datapath/RegisterFile/output[5]_2[10]} {CPU/datapath/RegisterFile/output[5]_2[11]} {CPU/datapath/RegisterFile/output[5]_2[12]} {CPU/datapath/RegisterFile/output[5]_2[13]} {CPU/datapath/RegisterFile/output[5]_2[14]} {CPU/datapath/RegisterFile/output[5]_2[15]} {CPU/datapath/RegisterFile/output[5]_2[16]} {CPU/datapath/RegisterFile/output[5]_2[17]} {CPU/datapath/RegisterFile/output[5]_2[18]} {CPU/datapath/RegisterFile/output[5]_2[19]} {CPU/datapath/RegisterFile/output[5]_2[20]} {CPU/datapath/RegisterFile/output[5]_2[21]} {CPU/datapath/RegisterFile/output[5]_2[22]} {CPU/datapath/RegisterFile/output[5]_2[23]} {CPU/datapath/RegisterFile/output[5]_2[24]} {CPU/datapath/RegisterFile/output[5]_2[25]} {CPU/datapath/RegisterFile/output[5]_2[26]} {CPU/datapath/RegisterFile/output[5]_2[27]} {CPU/datapath/RegisterFile/output[5]_2[28]} {CPU/datapath/RegisterFile/output[5]_2[29]} {CPU/datapath/RegisterFile/output[5]_2[30]} {CPU/datapath/RegisterFile/output[5]_2[31]}]]
set_property src_info {type:XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {CPU/datapath/RegisterFile/output[3]_4[0]} {CPU/datapath/RegisterFile/output[3]_4[1]} {CPU/datapath/RegisterFile/output[3]_4[2]} {CPU/datapath/RegisterFile/output[3]_4[3]} {CPU/datapath/RegisterFile/output[3]_4[4]} {CPU/datapath/RegisterFile/output[3]_4[5]} {CPU/datapath/RegisterFile/output[3]_4[6]} {CPU/datapath/RegisterFile/output[3]_4[7]} {CPU/datapath/RegisterFile/output[3]_4[8]} {CPU/datapath/RegisterFile/output[3]_4[9]} {CPU/datapath/RegisterFile/output[3]_4[10]} {CPU/datapath/RegisterFile/output[3]_4[11]} {CPU/datapath/RegisterFile/output[3]_4[12]} {CPU/datapath/RegisterFile/output[3]_4[13]} {CPU/datapath/RegisterFile/output[3]_4[14]} {CPU/datapath/RegisterFile/output[3]_4[15]} {CPU/datapath/RegisterFile/output[3]_4[16]} {CPU/datapath/RegisterFile/output[3]_4[17]} {CPU/datapath/RegisterFile/output[3]_4[18]} {CPU/datapath/RegisterFile/output[3]_4[19]} {CPU/datapath/RegisterFile/output[3]_4[20]} {CPU/datapath/RegisterFile/output[3]_4[21]} {CPU/datapath/RegisterFile/output[3]_4[22]} {CPU/datapath/RegisterFile/output[3]_4[23]} {CPU/datapath/RegisterFile/output[3]_4[24]} {CPU/datapath/RegisterFile/output[3]_4[25]} {CPU/datapath/RegisterFile/output[3]_4[26]} {CPU/datapath/RegisterFile/output[3]_4[27]} {CPU/datapath/RegisterFile/output[3]_4[28]} {CPU/datapath/RegisterFile/output[3]_4[29]} {CPU/datapath/RegisterFile/output[3]_4[30]} {CPU/datapath/RegisterFile/output[3]_4[31]}]]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {CPU/datapath/PC_out[0]} {CPU/datapath/PC_out[1]} {CPU/datapath/PC_out[2]} {CPU/datapath/PC_out[3]} {CPU/datapath/PC_out[4]} {CPU/datapath/PC_out[5]} {CPU/datapath/PC_out[6]} {CPU/datapath/PC_out[7]} {CPU/datapath/PC_out[8]} {CPU/datapath/PC_out[9]} {CPU/datapath/PC_out[10]} {CPU/datapath/PC_out[11]} {CPU/datapath/PC_out[12]} {CPU/datapath/PC_out[13]} {CPU/datapath/PC_out[14]} {CPU/datapath/PC_out[15]} {CPU/datapath/PC_out[16]} {CPU/datapath/PC_out[17]} {CPU/datapath/PC_out[18]} {CPU/datapath/PC_out[19]} {CPU/datapath/PC_out[20]} {CPU/datapath/PC_out[21]} {CPU/datapath/PC_out[22]} {CPU/datapath/PC_out[23]} {CPU/datapath/PC_out[24]} {CPU/datapath/PC_out[25]} {CPU/datapath/PC_out[26]} {CPU/datapath/PC_out[27]} {CPU/datapath/PC_out[28]} {CPU/datapath/PC_out[29]} {CPU/datapath/PC_out[30]} {CPU/datapath/PC_out[31]}]]
set_property src_info {type:XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {CPU/I_line[0]} {CPU/I_line[1]} {CPU/I_line[2]} {CPU/I_line[3]} {CPU/I_line[4]} {CPU/I_line[5]} {CPU/I_line[6]} {CPU/I_line[7]} {CPU/I_line[8]} {CPU/I_line[9]} {CPU/I_line[10]} {CPU/I_line[11]} {CPU/I_line[12]} {CPU/I_line[13]} {CPU/I_line[14]} {CPU/I_line[15]}]]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk_50]
