set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CFGBVS GND [current_design]






create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clkgen/inst/clk_50]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {CPU/datapath/RegisterFile/output[4]_3[0]} {CPU/datapath/RegisterFile/output[4]_3[1]} {CPU/datapath/RegisterFile/output[4]_3[2]} {CPU/datapath/RegisterFile/output[4]_3[3]} {CPU/datapath/RegisterFile/output[4]_3[4]} {CPU/datapath/RegisterFile/output[4]_3[5]} {CPU/datapath/RegisterFile/output[4]_3[6]} {CPU/datapath/RegisterFile/output[4]_3[7]} {CPU/datapath/RegisterFile/output[4]_3[8]} {CPU/datapath/RegisterFile/output[4]_3[9]} {CPU/datapath/RegisterFile/output[4]_3[10]} {CPU/datapath/RegisterFile/output[4]_3[11]} {CPU/datapath/RegisterFile/output[4]_3[12]} {CPU/datapath/RegisterFile/output[4]_3[13]} {CPU/datapath/RegisterFile/output[4]_3[14]} {CPU/datapath/RegisterFile/output[4]_3[15]} {CPU/datapath/RegisterFile/output[4]_3[16]} {CPU/datapath/RegisterFile/output[4]_3[17]} {CPU/datapath/RegisterFile/output[4]_3[18]} {CPU/datapath/RegisterFile/output[4]_3[19]} {CPU/datapath/RegisterFile/output[4]_3[20]} {CPU/datapath/RegisterFile/output[4]_3[21]} {CPU/datapath/RegisterFile/output[4]_3[22]} {CPU/datapath/RegisterFile/output[4]_3[23]} {CPU/datapath/RegisterFile/output[4]_3[24]} {CPU/datapath/RegisterFile/output[4]_3[25]} {CPU/datapath/RegisterFile/output[4]_3[26]} {CPU/datapath/RegisterFile/output[4]_3[27]} {CPU/datapath/RegisterFile/output[4]_3[28]} {CPU/datapath/RegisterFile/output[4]_3[29]} {CPU/datapath/RegisterFile/output[4]_3[30]} {CPU/datapath/RegisterFile/output[4]_3[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {CPU/datapath/RegisterFile/output[0]_7[0]} {CPU/datapath/RegisterFile/output[0]_7[1]} {CPU/datapath/RegisterFile/output[0]_7[2]} {CPU/datapath/RegisterFile/output[0]_7[3]} {CPU/datapath/RegisterFile/output[0]_7[4]} {CPU/datapath/RegisterFile/output[0]_7[5]} {CPU/datapath/RegisterFile/output[0]_7[6]} {CPU/datapath/RegisterFile/output[0]_7[7]} {CPU/datapath/RegisterFile/output[0]_7[8]} {CPU/datapath/RegisterFile/output[0]_7[9]} {CPU/datapath/RegisterFile/output[0]_7[10]} {CPU/datapath/RegisterFile/output[0]_7[11]} {CPU/datapath/RegisterFile/output[0]_7[12]} {CPU/datapath/RegisterFile/output[0]_7[13]} {CPU/datapath/RegisterFile/output[0]_7[14]} {CPU/datapath/RegisterFile/output[0]_7[15]} {CPU/datapath/RegisterFile/output[0]_7[16]} {CPU/datapath/RegisterFile/output[0]_7[17]} {CPU/datapath/RegisterFile/output[0]_7[18]} {CPU/datapath/RegisterFile/output[0]_7[19]} {CPU/datapath/RegisterFile/output[0]_7[20]} {CPU/datapath/RegisterFile/output[0]_7[21]} {CPU/datapath/RegisterFile/output[0]_7[22]} {CPU/datapath/RegisterFile/output[0]_7[23]} {CPU/datapath/RegisterFile/output[0]_7[24]} {CPU/datapath/RegisterFile/output[0]_7[25]} {CPU/datapath/RegisterFile/output[0]_7[26]} {CPU/datapath/RegisterFile/output[0]_7[27]} {CPU/datapath/RegisterFile/output[0]_7[28]} {CPU/datapath/RegisterFile/output[0]_7[29]} {CPU/datapath/RegisterFile/output[0]_7[30]} {CPU/datapath/RegisterFile/output[0]_7[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {CPU/datapath/RegisterFile/output[6]_1[0]} {CPU/datapath/RegisterFile/output[6]_1[1]} {CPU/datapath/RegisterFile/output[6]_1[2]} {CPU/datapath/RegisterFile/output[6]_1[3]} {CPU/datapath/RegisterFile/output[6]_1[4]} {CPU/datapath/RegisterFile/output[6]_1[5]} {CPU/datapath/RegisterFile/output[6]_1[6]} {CPU/datapath/RegisterFile/output[6]_1[7]} {CPU/datapath/RegisterFile/output[6]_1[8]} {CPU/datapath/RegisterFile/output[6]_1[9]} {CPU/datapath/RegisterFile/output[6]_1[10]} {CPU/datapath/RegisterFile/output[6]_1[11]} {CPU/datapath/RegisterFile/output[6]_1[12]} {CPU/datapath/RegisterFile/output[6]_1[13]} {CPU/datapath/RegisterFile/output[6]_1[14]} {CPU/datapath/RegisterFile/output[6]_1[15]} {CPU/datapath/RegisterFile/output[6]_1[16]} {CPU/datapath/RegisterFile/output[6]_1[17]} {CPU/datapath/RegisterFile/output[6]_1[18]} {CPU/datapath/RegisterFile/output[6]_1[19]} {CPU/datapath/RegisterFile/output[6]_1[20]} {CPU/datapath/RegisterFile/output[6]_1[21]} {CPU/datapath/RegisterFile/output[6]_1[22]} {CPU/datapath/RegisterFile/output[6]_1[23]} {CPU/datapath/RegisterFile/output[6]_1[24]} {CPU/datapath/RegisterFile/output[6]_1[25]} {CPU/datapath/RegisterFile/output[6]_1[26]} {CPU/datapath/RegisterFile/output[6]_1[27]} {CPU/datapath/RegisterFile/output[6]_1[28]} {CPU/datapath/RegisterFile/output[6]_1[29]} {CPU/datapath/RegisterFile/output[6]_1[30]} {CPU/datapath/RegisterFile/output[6]_1[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {CPU/datapath/RegisterFile/output[7]_0[0]} {CPU/datapath/RegisterFile/output[7]_0[1]} {CPU/datapath/RegisterFile/output[7]_0[2]} {CPU/datapath/RegisterFile/output[7]_0[3]} {CPU/datapath/RegisterFile/output[7]_0[4]} {CPU/datapath/RegisterFile/output[7]_0[5]} {CPU/datapath/RegisterFile/output[7]_0[6]} {CPU/datapath/RegisterFile/output[7]_0[7]} {CPU/datapath/RegisterFile/output[7]_0[8]} {CPU/datapath/RegisterFile/output[7]_0[9]} {CPU/datapath/RegisterFile/output[7]_0[10]} {CPU/datapath/RegisterFile/output[7]_0[11]} {CPU/datapath/RegisterFile/output[7]_0[12]} {CPU/datapath/RegisterFile/output[7]_0[13]} {CPU/datapath/RegisterFile/output[7]_0[14]} {CPU/datapath/RegisterFile/output[7]_0[15]} {CPU/datapath/RegisterFile/output[7]_0[16]} {CPU/datapath/RegisterFile/output[7]_0[17]} {CPU/datapath/RegisterFile/output[7]_0[18]} {CPU/datapath/RegisterFile/output[7]_0[19]} {CPU/datapath/RegisterFile/output[7]_0[20]} {CPU/datapath/RegisterFile/output[7]_0[21]} {CPU/datapath/RegisterFile/output[7]_0[22]} {CPU/datapath/RegisterFile/output[7]_0[23]} {CPU/datapath/RegisterFile/output[7]_0[24]} {CPU/datapath/RegisterFile/output[7]_0[25]} {CPU/datapath/RegisterFile/output[7]_0[26]} {CPU/datapath/RegisterFile/output[7]_0[27]} {CPU/datapath/RegisterFile/output[7]_0[28]} {CPU/datapath/RegisterFile/output[7]_0[29]} {CPU/datapath/RegisterFile/output[7]_0[30]} {CPU/datapath/RegisterFile/output[7]_0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {CPU/datapath/AdressI[0]} {CPU/datapath/AdressI[1]} {CPU/datapath/AdressI[2]} {CPU/datapath/AdressI[3]} {CPU/datapath/AdressI[4]} {CPU/datapath/AdressI[5]} {CPU/datapath/AdressI[6]} {CPU/datapath/AdressI[7]} {CPU/datapath/AdressI[8]} {CPU/datapath/AdressI[9]} {CPU/datapath/AdressI[10]} {CPU/datapath/AdressI[11]} {CPU/datapath/AdressI[12]} {CPU/datapath/AdressI[13]} {CPU/datapath/AdressI[14]} {CPU/datapath/AdressI[15]} {CPU/datapath/AdressI[16]} {CPU/datapath/AdressI[17]} {CPU/datapath/AdressI[18]} {CPU/datapath/AdressI[19]} {CPU/datapath/AdressI[20]} {CPU/datapath/AdressI[21]} {CPU/datapath/AdressI[22]} {CPU/datapath/AdressI[23]} {CPU/datapath/AdressI[24]} {CPU/datapath/AdressI[25]} {CPU/datapath/AdressI[26]} {CPU/datapath/AdressI[27]} {CPU/datapath/AdressI[28]} {CPU/datapath/AdressI[29]} {CPU/datapath/AdressI[30]} {CPU/datapath/AdressI[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {CPU/datapath/RegisterFile/output[1]_6[0]} {CPU/datapath/RegisterFile/output[1]_6[1]} {CPU/datapath/RegisterFile/output[1]_6[2]} {CPU/datapath/RegisterFile/output[1]_6[3]} {CPU/datapath/RegisterFile/output[1]_6[4]} {CPU/datapath/RegisterFile/output[1]_6[5]} {CPU/datapath/RegisterFile/output[1]_6[6]} {CPU/datapath/RegisterFile/output[1]_6[7]} {CPU/datapath/RegisterFile/output[1]_6[8]} {CPU/datapath/RegisterFile/output[1]_6[9]} {CPU/datapath/RegisterFile/output[1]_6[10]} {CPU/datapath/RegisterFile/output[1]_6[11]} {CPU/datapath/RegisterFile/output[1]_6[12]} {CPU/datapath/RegisterFile/output[1]_6[13]} {CPU/datapath/RegisterFile/output[1]_6[14]} {CPU/datapath/RegisterFile/output[1]_6[15]} {CPU/datapath/RegisterFile/output[1]_6[16]} {CPU/datapath/RegisterFile/output[1]_6[17]} {CPU/datapath/RegisterFile/output[1]_6[18]} {CPU/datapath/RegisterFile/output[1]_6[19]} {CPU/datapath/RegisterFile/output[1]_6[20]} {CPU/datapath/RegisterFile/output[1]_6[21]} {CPU/datapath/RegisterFile/output[1]_6[22]} {CPU/datapath/RegisterFile/output[1]_6[23]} {CPU/datapath/RegisterFile/output[1]_6[24]} {CPU/datapath/RegisterFile/output[1]_6[25]} {CPU/datapath/RegisterFile/output[1]_6[26]} {CPU/datapath/RegisterFile/output[1]_6[27]} {CPU/datapath/RegisterFile/output[1]_6[28]} {CPU/datapath/RegisterFile/output[1]_6[29]} {CPU/datapath/RegisterFile/output[1]_6[30]} {CPU/datapath/RegisterFile/output[1]_6[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {CPU/datapath/RegisterFile/output[2]_5[0]} {CPU/datapath/RegisterFile/output[2]_5[1]} {CPU/datapath/RegisterFile/output[2]_5[2]} {CPU/datapath/RegisterFile/output[2]_5[3]} {CPU/datapath/RegisterFile/output[2]_5[4]} {CPU/datapath/RegisterFile/output[2]_5[5]} {CPU/datapath/RegisterFile/output[2]_5[6]} {CPU/datapath/RegisterFile/output[2]_5[7]} {CPU/datapath/RegisterFile/output[2]_5[8]} {CPU/datapath/RegisterFile/output[2]_5[9]} {CPU/datapath/RegisterFile/output[2]_5[10]} {CPU/datapath/RegisterFile/output[2]_5[11]} {CPU/datapath/RegisterFile/output[2]_5[12]} {CPU/datapath/RegisterFile/output[2]_5[13]} {CPU/datapath/RegisterFile/output[2]_5[14]} {CPU/datapath/RegisterFile/output[2]_5[15]} {CPU/datapath/RegisterFile/output[2]_5[16]} {CPU/datapath/RegisterFile/output[2]_5[17]} {CPU/datapath/RegisterFile/output[2]_5[18]} {CPU/datapath/RegisterFile/output[2]_5[19]} {CPU/datapath/RegisterFile/output[2]_5[20]} {CPU/datapath/RegisterFile/output[2]_5[21]} {CPU/datapath/RegisterFile/output[2]_5[22]} {CPU/datapath/RegisterFile/output[2]_5[23]} {CPU/datapath/RegisterFile/output[2]_5[24]} {CPU/datapath/RegisterFile/output[2]_5[25]} {CPU/datapath/RegisterFile/output[2]_5[26]} {CPU/datapath/RegisterFile/output[2]_5[27]} {CPU/datapath/RegisterFile/output[2]_5[28]} {CPU/datapath/RegisterFile/output[2]_5[29]} {CPU/datapath/RegisterFile/output[2]_5[30]} {CPU/datapath/RegisterFile/output[2]_5[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {CPU/datapath/RegisterFile/output[5]_2[0]} {CPU/datapath/RegisterFile/output[5]_2[1]} {CPU/datapath/RegisterFile/output[5]_2[2]} {CPU/datapath/RegisterFile/output[5]_2[3]} {CPU/datapath/RegisterFile/output[5]_2[4]} {CPU/datapath/RegisterFile/output[5]_2[5]} {CPU/datapath/RegisterFile/output[5]_2[6]} {CPU/datapath/RegisterFile/output[5]_2[7]} {CPU/datapath/RegisterFile/output[5]_2[8]} {CPU/datapath/RegisterFile/output[5]_2[9]} {CPU/datapath/RegisterFile/output[5]_2[10]} {CPU/datapath/RegisterFile/output[5]_2[11]} {CPU/datapath/RegisterFile/output[5]_2[12]} {CPU/datapath/RegisterFile/output[5]_2[13]} {CPU/datapath/RegisterFile/output[5]_2[14]} {CPU/datapath/RegisterFile/output[5]_2[15]} {CPU/datapath/RegisterFile/output[5]_2[16]} {CPU/datapath/RegisterFile/output[5]_2[17]} {CPU/datapath/RegisterFile/output[5]_2[18]} {CPU/datapath/RegisterFile/output[5]_2[19]} {CPU/datapath/RegisterFile/output[5]_2[20]} {CPU/datapath/RegisterFile/output[5]_2[21]} {CPU/datapath/RegisterFile/output[5]_2[22]} {CPU/datapath/RegisterFile/output[5]_2[23]} {CPU/datapath/RegisterFile/output[5]_2[24]} {CPU/datapath/RegisterFile/output[5]_2[25]} {CPU/datapath/RegisterFile/output[5]_2[26]} {CPU/datapath/RegisterFile/output[5]_2[27]} {CPU/datapath/RegisterFile/output[5]_2[28]} {CPU/datapath/RegisterFile/output[5]_2[29]} {CPU/datapath/RegisterFile/output[5]_2[30]} {CPU/datapath/RegisterFile/output[5]_2[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {CPU/datapath/RegisterFile/output[3]_4[0]} {CPU/datapath/RegisterFile/output[3]_4[1]} {CPU/datapath/RegisterFile/output[3]_4[2]} {CPU/datapath/RegisterFile/output[3]_4[3]} {CPU/datapath/RegisterFile/output[3]_4[4]} {CPU/datapath/RegisterFile/output[3]_4[5]} {CPU/datapath/RegisterFile/output[3]_4[6]} {CPU/datapath/RegisterFile/output[3]_4[7]} {CPU/datapath/RegisterFile/output[3]_4[8]} {CPU/datapath/RegisterFile/output[3]_4[9]} {CPU/datapath/RegisterFile/output[3]_4[10]} {CPU/datapath/RegisterFile/output[3]_4[11]} {CPU/datapath/RegisterFile/output[3]_4[12]} {CPU/datapath/RegisterFile/output[3]_4[13]} {CPU/datapath/RegisterFile/output[3]_4[14]} {CPU/datapath/RegisterFile/output[3]_4[15]} {CPU/datapath/RegisterFile/output[3]_4[16]} {CPU/datapath/RegisterFile/output[3]_4[17]} {CPU/datapath/RegisterFile/output[3]_4[18]} {CPU/datapath/RegisterFile/output[3]_4[19]} {CPU/datapath/RegisterFile/output[3]_4[20]} {CPU/datapath/RegisterFile/output[3]_4[21]} {CPU/datapath/RegisterFile/output[3]_4[22]} {CPU/datapath/RegisterFile/output[3]_4[23]} {CPU/datapath/RegisterFile/output[3]_4[24]} {CPU/datapath/RegisterFile/output[3]_4[25]} {CPU/datapath/RegisterFile/output[3]_4[26]} {CPU/datapath/RegisterFile/output[3]_4[27]} {CPU/datapath/RegisterFile/output[3]_4[28]} {CPU/datapath/RegisterFile/output[3]_4[29]} {CPU/datapath/RegisterFile/output[3]_4[30]} {CPU/datapath/RegisterFile/output[3]_4[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {CPU/datapath/PC_out[0]} {CPU/datapath/PC_out[1]} {CPU/datapath/PC_out[2]} {CPU/datapath/PC_out[3]} {CPU/datapath/PC_out[4]} {CPU/datapath/PC_out[5]} {CPU/datapath/PC_out[6]} {CPU/datapath/PC_out[7]} {CPU/datapath/PC_out[8]} {CPU/datapath/PC_out[9]} {CPU/datapath/PC_out[10]} {CPU/datapath/PC_out[11]} {CPU/datapath/PC_out[12]} {CPU/datapath/PC_out[13]} {CPU/datapath/PC_out[14]} {CPU/datapath/PC_out[15]} {CPU/datapath/PC_out[16]} {CPU/datapath/PC_out[17]} {CPU/datapath/PC_out[18]} {CPU/datapath/PC_out[19]} {CPU/datapath/PC_out[20]} {CPU/datapath/PC_out[21]} {CPU/datapath/PC_out[22]} {CPU/datapath/PC_out[23]} {CPU/datapath/PC_out[24]} {CPU/datapath/PC_out[25]} {CPU/datapath/PC_out[26]} {CPU/datapath/PC_out[27]} {CPU/datapath/PC_out[28]} {CPU/datapath/PC_out[29]} {CPU/datapath/PC_out[30]} {CPU/datapath/PC_out[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 16 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {CPU/I_line[0]} {CPU/I_line[1]} {CPU/I_line[2]} {CPU/I_line[3]} {CPU/I_line[4]} {CPU/I_line[5]} {CPU/I_line[6]} {CPU/I_line[7]} {CPU/I_line[8]} {CPU/I_line[9]} {CPU/I_line[10]} {CPU/I_line[11]} {CPU/I_line[12]} {CPU/I_line[13]} {CPU/I_line[14]} {CPU/I_line[15]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_50]
